### ISSUE TITLE
Feature Request: Mouse/Cursos Icons

### ISSUE THREAD

**Issue by aarproducoes** [jneem/scribl#7] opened 2021-02-02 13:02 UTC
Hi! Nice software.
Very useful.

So, there is a way to add a check box to show cursor on monitor  while recording?
Some time is difficult to imagine or locale where will start the next line...
The options:
. view cursor only on monitor, but not recorded to the video;
. view cursor on monitor and recorded in the video;

The plus feature:
. select different cursors icons: point, cross, hand, hand with pen/pencil, a feather pen
. for hand, hand with pen/pencil and feather pen, options for left or right handed/side

Thanks.

:. using Scribl on Pop!_OS 20.04 flatpak | laptop i74810mq | 16GB ram

**Comment by jneem** [comment] 2021-02-02 18:42
Thanks for the report! What version of the flatpak are you using? Because I thought I fixed the disappearing cursor issue with 0.3.1...

Could you also try building from source? I've had issues getting the flatpak builds to show custom mouse cursors, and I haven't found the time to track down the cause yet.

**Comment by aarproducoes** [comment] 2021-02-03 02:12
Flatpak 1.8.5
Scribl, ink.scribl.Scribl, 0.3.1, stable, flathub, user
I will try setup some flatpak permissions on and off to check if cursors appears.

**Comment by aarproducoes** [comment] 2021-02-03 02:45
Hi again!
Found!
In flatpak the permission for:
Inter-process communications
share=ipc

must be disable be default.
in the installation this options is On by default. So, the mouse cursor is not displayed.




https://user-images.githubusercontent.com/29419170/106690510-b3324e00-65b0-11eb-8c69-28e2540ccff2.mp4

**Comment by jneem** [comment] 2021-02-03 03:45
Thanks for the detective work! I'm confused, though, because the documentation [here](https://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions) says that `share=ipc` is necessary for X11. Are you using X11 or wayland?

**Comment by aarproducoes** [comment] 2021-02-03 04:20
On a X11 env.

**Comment by jneem** [comment] 2021-02-05 05:10
Ok, I don't understand it because all the documentation I could find says that you need share=ipc, but I checked on my system and the fix works here too.

Could you check the latest flathub package? It should be fixed.

**Comment by aarproducoes** [comment] 2021-02-05 14:46
Hello!
Yep. I will update my flatpak package.
Also, i'll make a fresh installation using flatpak package on another notebook, just in case to know if the new version works out of the box since first install.

**Comment by aarproducoes** [comment] 2021-02-05 16:09
So, tested update and fresh install of Scribl.

On my default notebook:
Flatpak update = ok
	.running/open with share=ipc off = pencil icon works
	.running/open with share=ipc on = pencil icon missing

On another notebook
Fresh install of Scribl flatpak:
	.first open and using = works nice!

**Closed as completed** 2021-02-05 20:41 UTC
